/**
 * GraphQL Codegen configuration placeholder.
 *
 * This will be used by @graphql-codegen/cli when the packages/api-client
 * package is created. Dependencies are not installed yet.
 *
 * Usage (future): npx graphql-codegen --config codegen.ts
 */
export default {
  schema: 'schema.gql', // auto-generated by NestJS code-first
  generates: {
    'src/graphql.generated.ts': {
      plugins: ['typescript'],
    },
  },
};
